### PR TITLE
enhance computable lookup perf

### PR DESCRIPTION
**Pull request by hackape**
hash table key lookup is noticeably faster than `sourceDataTypes.includes`.

### CODE REVIEW

**Comment by thaaddeus** [comment]
Thanks! I'll review it. Do you have any benchmark that should show that speed improvement? I know this is the case in general case, but I just wonder since in practice `sourceDataTypes` array is very small (like one element or two) it could be that it's not that much slower than lookup or in theory could be even faster (depending how v8 optimizes that path).

**Comment by hackape** [comment]
I had this benchmark setup: each sample runs 1000 iterations, and average over 50 samples. Measurement is done using this lib [@thi.ng/bench](https://unpkg.com/@thi.ng/bench@2.0.21/lib/index.js) (very minimalist lib) with some basic wrapper scripts. Here's the result.

For 1 computable of `sourceDataType = ['bookChange']` run against 100 messages of type `bookChange`.
```
benchmarking "original.js"... 
[summary] min: 27714 ops/s, max: 32305 ops/s, avg: 29902.54 ops/s

benchmarking "enhanced.js"... 
[summary] min: 28933 ops/s, max: 32516 ops/s, avg: 30277.08 ops/s

[report] =============
enhanced.js 30277.08 ops/s fatest
original.js 29902.54 ops/s 1.24% slower
```

For 2 computables of `sourceDataType = ['bookChange']` and `sourceDataType = ['trade']` run against 200 messages of type `bookChange` and `trade` interleaved.

```
benchmarking "original.js"... 
[summary] min: 14071 ops/s, max: 15305 ops/s, avg: 14298.50 ops/s

benchmarking "enhanced.js"... 
[summary] min: 15105 ops/s, max: 16281 ops/s, avg: 15307.22 ops/s

[report] =============
enhanced.js 15307.22 ops/s fatest
original.js 14298.50 ops/s 6.59% slower
```

For 1 computable of `sourceDataType = ['bookChange', 'trade']` run against 200 messages of type `bookChange` and `trade` interleaved.

```
benchmarking "original.js"... 
[summary] min: 15770 ops/s, max: 16683 ops/s, avg: 15727.18 ops/s

benchmarking "enhanced.js"... 
[summary] min: 15263 ops/s, max: 16328 ops/s, avg: 15201.24 ops/s

[report] =============
original.js 15727.18 ops/s fatest
enhanced.js 15201.24 ops/s 3.34% slower
```

For 4 computables, 2 of `sourceDataType = ['bookChange'] and 2 of `sourceDataType = ['trade']` run against 200 messages of type `bookChange` and `trade` interleaved.

```
benchmarking "original.js"... 
[summary] min: 8829 ops/s, max: 10694 ops/s, avg: 10040.80 ops/s

benchmarking "enhanced.js"... 
[summary] min: 11082 ops/s, max: 11568 ops/s, avg: 10865.02 ops/s

[report] =============
enhanced.js 10865.02 ops/s fatest
original.js 10040.80 ops/s 7.59% slower
```

[benchmark.zip](https://github.com/tardis-dev/tardis-node/files/5346815/benchmark.zip)

**Comment by hackape** [comment]
Sorry I forgot to include the wrapper script in the above zip file. Github don't accept uploading js file so I just paste here.

You can exec `node bench.js original.js enhanced.js`. Change `computables.js` and `messages.js` to get different setup.

**bench.js**
```js
// @ts-check
const path = require("path");
const readline = require("readline");
const { benchmark } = require("@thi.ng/bench");

const backspace = () => readline.moveCursor(process.stdout, -1, 0);

const config = {
  iter: 1000,
  warmup: 50,
  sample: 50,
  verbose: false,
};

function _loadTestCase(acc, filepath, testcase, index) {
  if (Array.isArray(testcase)) {
    testcase.forEach((testcase, index) => {
      _loadTestCase(acc, filepath, testcase, index);
    });
  } else {
    let suffix = "";
    if (typeof index === "number") {
      suffix = ` (Case ${index + 1})`;
    }

    testcase = { ...testcase, ops: new Array(config.sample) };
    if (typeof testcase.run !== "function") {
      throw Error(
        `Error: Bad test case '${filepath}', must export \`run\` function.`
      );
    }
    if (typeof testcase.title !== "string") {
      const basename = path.basename(filepath);
      testcase.title = basename + suffix;
    }
    testcase.filepath = filepath;
    acc.push(testcase);
  }
  return acc;
}

function loadTestCases() {
  try {
    const args = process.argv.slice(2);
    return args.reduce((acc, filename) => {
      const filepath = path.resolve(filename);

      const testcase = require(filepath);
      return _loadTestCase(acc, filepath, testcase);
    }, []);
  } catch (e) {
    console.error(e.message);
    process.exit(1);
  }
}

function sleep(ms) {
  var resolve;
  const p = new Promise((r) => (resolve = r));
  setTimeout(resolve, ms);
  return p;
}

function spinnerFactory() {
  const spinner = "|/-\\";
  const spinnerLen = spinner.length;
  let spinnerCount = 0;
  return () => spinner[spinnerCount++ % spinnerLen];
}

function logHeaderFactory(title, verbose) {
  if (verbose) {
    let done = false;
    return () => {
      if (done) return;
      console.log(`benchmarking "${title}"...`);
      done = true;
    };
  } else {
    const spin = spinnerFactory();
    let init = false;
    return (end) => {
      if (end) {
        backspace();
        process.stdout.write(" \n");
        return;
      } else if (init) {
        backspace();
        process.stdout.write(spin());
      } else {
        process.stdout.write(`benchmarking "${title}"...${spin()}`);
        init = true;
      }
    };
  }
}

async function main() {
  const testcases = loadTestCases();

  for (const testcase of testcases) {
    let sampleIndex = 0;
    const logHeader = logHeaderFactory(testcase.title, config.verbose);
    while (sampleIndex < config.sample) {
      logHeader();
      runSample(testcase, sampleIndex++, config);
      global.gc();
    }
    logHeader(true);

    const stat = getOpsStat(testcase.ops);
    testcase.stat = stat;
    console.log(
      `[summary] min: ${stat.min} ops/s, max: ${
        stat.max
      } ops/s, avg: ${stat.avg.toFixed(2)} ops/s\n`
    );

    await sleep(100);
  }

  getReport(testcases);
}

function getReport(testcases) {
  testcases.sort((a, b) => b.stat.avg - a.stat.avg);
  const fastest = testcases[0];
  testcases.forEach((testcase) => {
    if (testcase === fastest) testcase.lag = 0;
    const lag = 1 - testcase.stat.avg / fastest.stat.avg;
    testcase.lag = lag;
  });

  console.log("[report] =============");
  testcases.forEach((testcase) => {
    const remark = testcase.lag
      ? `${(testcase.lag * 100).toFixed(2)}% slower`
      : "fatest";
    console.log(
      `${testcase.title} ${testcase.stat.avg.toFixed(2)} ops/s ${remark}`
    );
  });
}

function getOpsStat(_ops) {
  const ops = _ops.slice();
  // remove the highest and lowest results:
  ops.sort();
  ops.pop();
  ops.shift();

  const stat = ops.reduce(
    (acc, op) => {
      acc.avg += op / config.sample;
      acc.min = Math.min(acc.min, op);
      acc.max = Math.max(acc.max, op);
      return acc;
    },
    { min: Infinity, max: 0, avg: 0 }
  );

  stat.avg = stat.avg;
  return stat;
}

function runSample(testcase, i, config) {
  if (config.verbose) process.stdout.write(`[${i + 1}] ${testcase.title}...`);
  const result = benchmark(testcase.run, {
    title: testcase.title,
    warmup: config.warmup,
    iter: config.iter,
    print: false,
  });

  testcase.ops[i] = Math.round((result.iter * 1000) / result.total);

  if (config.verbose) {
    console.log(
      `${result.iter} iterations, took ${result.total.toFixed(2)}ms, ${
        testcase.ops[i]
      } ops/s`
    );
  }
}

main();
```

**Comment by thaaddeus** [comment]
awesome! thanks!

**Comment by thaaddeus** [comment]
released in  v12.2.1

**Pull request merged**
